import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { Providers } from "../provider";
import '@rainbow-me/rainbowkit/styles.css';
import { Web3AuthProvider } from '../components/Web3AuthProvider';
import '@rainbow-me/rainbowkit/styles.css';

const spaceGrotesk = Space_Grotesk({
  variable: "--space-grotesk",
  subsets: ["latin"],
  weight: "400", // Add a valid weight value
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} antialiased`}
      >
        <Web3AuthProvider>
          {/* <Providers> */}
          {children}
          {/* </Providers> */}
        </Web3AuthProvider>
      </body>
    </html>
  );
}
